lazyPaladinLoad.metadata:updateRevisionFromKeyword("$Revision: 715 $")

function lazyPaladinLoad.LoadPaladinLocalization(locale)
	
	lazyPaladinLocale.enUS.ACTION_TTS.concAura      = "Concentration Aura"
	lazyPaladinLocale.enUS.ACTION_TTS.devAura       = "Devotion Aura"
	lazyPaladinLocale.enUS.ACTION_TTS.fireAura      = "Fire Resistance Aura"
	lazyPaladinLocale.enUS.ACTION_TTS.frostAura     = "Frost Resistance Aura"
	lazyPaladinLocale.enUS.ACTION_TTS.retAura       = "Retribution Aura"
	lazyPaladinLocale.enUS.ACTION_TTS.sanctAura     = "Sanctity Aura"
	lazyPaladinLocale.enUS.ACTION_TTS.shadowAura    = "Shadow Resistance Aura"
	lazyPaladinLocale.enUS.ACTION_TTS.blessFree     = "Blessing of Freedom"
	lazyPaladinLocale.enUS.ACTION_TTS.blessKings    = "Blessing of Kings"
	lazyPaladinLocale.enUS.ACTION_TTS.blessLight    = "Blessing of Light"
	lazyPaladinLocale.enUS.ACTION_TTS.blessMight    = "Blessing of Might"
	lazyPaladinLocale.enUS.ACTION_TTS.blessProt     = "Blessing of Protection"
	lazyPaladinLocale.enUS.ACTION_TTS.blessSac      = "Blessing of Sacrifice"
	lazyPaladinLocale.enUS.ACTION_TTS.blessSlv      = "Blessing of Salvation"
	lazyPaladinLocale.enUS.ACTION_TTS.blessSnct     = "Blessing of Sanctuary"
	lazyPaladinLocale.enUS.ACTION_TTS.blessWisdom   = "Blessing of Wisdom"
	lazyPaladinLocale.enUS.ACTION_TTS.cleanse       = "Cleanse"
	lazyPaladinLocale.enUS.ACTION_TTS.consecrate    = "Consecration"
	lazyPaladinLocale.enUS.ACTION_TTS.divFavor      = "Divine Favor"
	lazyPaladinLocale.enUS.ACTION_TTS.divIntr       = "Divine Intervention"
	lazyPaladinLocale.enUS.ACTION_TTS.divProt       = "Divine Protection"
	lazyPaladinLocale.enUS.ACTION_TTS.divShield     = "Divine Shield"
	lazyPaladinLocale.enUS.ACTION_TTS.exorcism      = "Exorcism"
	lazyPaladinLocale.enUS.ACTION_TTS.flashLight    = "Flash of Light"
	lazyPaladinLocale.enUS.ACTION_TTS.gBlessKings   = "Greater Blessing of Kings"
	lazyPaladinLocale.enUS.ACTION_TTS.gBlessLight   = "Greater Blessing of Light"
	lazyPaladinLocale.enUS.ACTION_TTS.gBlessMight   = "Greater Blessing of Might"
	lazyPaladinLocale.enUS.ACTION_TTS.gBlessSlv     = "Greater Blessing of Salvation"
	lazyPaladinLocale.enUS.ACTION_TTS.gBlessSnct    = "Greater Blessing of Sanctuary"
	lazyPaladinLocale.enUS.ACTION_TTS.gBlessWisdom  = "Greater Blessing of Wisdom"
	lazyPaladinLocale.enUS.ACTION_TTS.hmrJustice    = "Hammer of Justice"
	lazyPaladinLocale.enUS.ACTION_TTS.hmrWrath      = "Hammer of Wrath"
	lazyPaladinLocale.enUS.ACTION_TTS.holyLight     = "Holy Light"
	lazyPaladinLocale.enUS.ACTION_TTS.holyShield    = "Holy Shield"
	lazyPaladinLocale.enUS.ACTION_TTS.holyShock     = "Holy Shock"
	lazyPaladinLocale.enUS.ACTION_TTS.holyWrath     = "Holy Wrath"
	lazyPaladinLocale.enUS.ACTION_TTS.judge         = "Judgement"
	lazyPaladinLocale.enUS.ACTION_TTS.layOnHands    = "Lay on Hands"
	lazyPaladinLocale.enUS.ACTION_TTS.purify        = "Purify"
	lazyPaladinLocale.enUS.ACTION_TTS.redemption    = "Redemption"
	lazyPaladinLocale.enUS.ACTION_TTS.repentance    = "Repentance"
	lazyPaladinLocale.enUS.ACTION_TTS.rightFury     = "Righteous Fury"
	lazyPaladinLocale.enUS.ACTION_TTS.sealCommand   = "Seal of Command"
	lazyPaladinLocale.enUS.ACTION_TTS.sealCrusader  = "Seal of the Crusader"
	lazyPaladinLocale.enUS.ACTION_TTS.sealJustice   = "Seal of Justice"
	lazyPaladinLocale.enUS.ACTION_TTS.sealLight     = "Seal of Light"
	lazyPaladinLocale.enUS.ACTION_TTS.sealRight     = "Seal of Righteousness"
	lazyPaladinLocale.enUS.ACTION_TTS.sealWisdom    = "Seal of Wisdom"
	lazyPaladinLocale.enUS.ACTION_TTS.senseUndead   = "Sense Undead"
	lazyPaladinLocale.enUS.ACTION_TTS.smnCharger	= "Summon Charger"
	lazyPaladinLocale.enUS.ACTION_TTS.smnWarhorse   = "Summon Warhorse"
	lazyPaladinLocale.enUS.ACTION_TTS.turnUndead    = "Turn Undead"
	
	-- LazyPaladin.lua
	PALADIN_ADDON_LOADED = " loaded. Powered by "
	
	-- ParsePaladin.lua
	function lazyPaladin.CustomLocaleHelp() return [[<H2>Paladin Criteria:</H2>]] end
	
	if (locale == "ruRU") then
		
		lazyPaladinLocale.ruRU.ACTION_TTS.concAura      = "Аура сосредоточенности"
		lazyPaladinLocale.ruRU.ACTION_TTS.devAura       = "Аура благочестия"
		lazyPaladinLocale.ruRU.ACTION_TTS.fireAura      = "Аура сопротивления огню"
		lazyPaladinLocale.ruRU.ACTION_TTS.frostAura     = "Аура сопротивления магии льда"
		lazyPaladinLocale.ruRU.ACTION_TTS.retAura       = "Аура воздаяния"
		lazyPaladinLocale.ruRU.ACTION_TTS.sanctAura     = "Аура святости"
		lazyPaladinLocale.ruRU.ACTION_TTS.shadowAura    = "Аура сопротивления темной магии"
		lazyPaladinLocale.ruRU.ACTION_TTS.blessFree     = "Благословение свободы"
		lazyPaladinLocale.ruRU.ACTION_TTS.blessKings    = "Благословение королей"
		lazyPaladinLocale.ruRU.ACTION_TTS.blessLight    = "Благословение Света"
		lazyPaladinLocale.ruRU.ACTION_TTS.blessMight    = "Благословение могущества"
		lazyPaladinLocale.ruRU.ACTION_TTS.blessProt     = "Благословение защиты"
		lazyPaladinLocale.ruRU.ACTION_TTS.blessSac      = "Благословение жертвенности"
		lazyPaladinLocale.ruRU.ACTION_TTS.blessSlv      = "Благословение спасения"
		lazyPaladinLocale.ruRU.ACTION_TTS.blessSnct     = "Благословение неприкосновенности"
		lazyPaladinLocale.ruRU.ACTION_TTS.blessWisdom   = "Благословение мудрости"
		lazyPaladinLocale.ruRU.ACTION_TTS.cleanse       = "Очищение"
		lazyPaladinLocale.ruRU.ACTION_TTS.consecrate    = "Освящение"
		lazyPaladinLocale.ruRU.ACTION_TTS.divFavor      = "Божественное одобрение"
		lazyPaladinLocale.ruRU.ACTION_TTS.divIntr       = "Божественное вмешательство"
		lazyPaladinLocale.ruRU.ACTION_TTS.divProt       = "Божественная защита"
		lazyPaladinLocale.ruRU.ACTION_TTS.divShield     = "Божественный щит"
		lazyPaladinLocale.ruRU.ACTION_TTS.exorcism      = "Экзорцизм"
		lazyPaladinLocale.ruRU.ACTION_TTS.flashLight    = "Вспышка Света"
		lazyPaladinLocale.ruRU.ACTION_TTS.gBlessKings   = "Великое благословение королей"
		lazyPaladinLocale.ruRU.ACTION_TTS.gBlessLight   = "Великое благословение Света"
		lazyPaladinLocale.ruRU.ACTION_TTS.gBlessMight   = "Великое благословение могущества"
		lazyPaladinLocale.ruRU.ACTION_TTS.gBlessSlv     = "Великое благословение спасения"
		lazyPaladinLocale.ruRU.ACTION_TTS.gBlessSnct    = "Великое благословение неприкосновенности"
		lazyPaladinLocale.ruRU.ACTION_TTS.gBlessWisdom  = "Великое благословение мудрости"
		lazyPaladinLocale.ruRU.ACTION_TTS.hmrJustice    = "Молот правосудия"
		lazyPaladinLocale.ruRU.ACTION_TTS.hmrWrath      = "Молот гнева"
		lazyPaladinLocale.ruRU.ACTION_TTS.holyLight     = "Свет небес"
		lazyPaladinLocale.ruRU.ACTION_TTS.holyShield    = "Щит небес"
		lazyPaladinLocale.ruRU.ACTION_TTS.holyShock     = "Шок небес"
		lazyPaladinLocale.ruRU.ACTION_TTS.holyWrath     = "Гнев небес"
		lazyPaladinLocale.ruRU.ACTION_TTS.judge         = "Правосудие"
		lazyPaladinLocale.ruRU.ACTION_TTS.layOnHands    = "Возложение рук"
		lazyPaladinLocale.ruRU.ACTION_TTS.purify        = "Омовение"
		lazyPaladinLocale.ruRU.ACTION_TTS.redemption    = "Искупление"
		lazyPaladinLocale.ruRU.ACTION_TTS.repentance    = "Покаяние"
		lazyPaladinLocale.ruRU.ACTION_TTS.rightFury     = "Праведное неистовство"
		lazyPaladinLocale.ruRU.ACTION_TTS.sealCommand   = "Печать повиновения"
		lazyPaladinLocale.ruRU.ACTION_TTS.sealCrusader  = "Печать воина Света"
		lazyPaladinLocale.ruRU.ACTION_TTS.sealJustice   = "Печать справедливости"
		lazyPaladinLocale.ruRU.ACTION_TTS.sealLight     = "Печать Света"
		lazyPaladinLocale.ruRU.ACTION_TTS.sealRight     = "Печать праведности"
		lazyPaladinLocale.ruRU.ACTION_TTS.sealWisdom    = "Печать мудрости"
		lazyPaladinLocale.ruRU.ACTION_TTS.senseUndead   = "Чутье на нежить"
		lazyPaladinLocale.ruRU.ACTION_TTS.smnCharger	= "Призыв скакуна"
		lazyPaladinLocale.ruRU.ACTION_TTS.smnWarhorse   = "Призыв боевого коня"
		lazyPaladinLocale.ruRU.ACTION_TTS.turnUndead    = "Изгнание нежити"
		
		-- LazyPaladin.lua
		PALADIN_ADDON_LOADED = " загружен. Работает от "
		
		-- ParsePaladin.lua
		function lazyPaladin.CustomLocaleHelp() return [[H2>Критерии Паладина:</H2>]] end
		
	end
end
