lazyMageLoad.metadata:updateRevisionFromKeyword("$Revision: 689 $")

function lazyMageLoad.LoadMageLocalization(locale)
	
	lazyMageLocale.enUS.ACTION_TTS.amplifyMagic     = "Amplify Magic"
	lazyMageLocale.enUS.ACTION_TTS.arcanePower      = "Arcane Power"
	lazyMageLocale.enUS.ACTION_TTS.blastWave        = "Blast Wave"
	lazyMageLocale.enUS.ACTION_TTS.blink            = "Blink"
	lazyMageLocale.enUS.ACTION_TTS.blizzard         = "Blizzard"
	lazyMageLocale.enUS.ACTION_TTS.brilliance       = "Arcane Brilliance"
	lazyMageLocale.enUS.ACTION_TTS.coldSnap         = "Cold Snap"
	lazyMageLocale.enUS.ACTION_TTS.combustion       = "Combustion"
	lazyMageLocale.enUS.ACTION_TTS.coneCold         = "Cone of Cold"
	lazyMageLocale.enUS.ACTION_TTS.conjureAgate     = "Conjure Mana Agate"
	lazyMageLocale.enUS.ACTION_TTS.conjureCitrine   = "Conjure Mana Citrine"
	lazyMageLocale.enUS.ACTION_TTS.conjureFood      = "Conjure Food"
	lazyMageLocale.enUS.ACTION_TTS.conjureJade      = "Conjure Mana Jade"
	lazyMageLocale.enUS.ACTION_TTS.conjureRuby      = "Conjure Mana Ruby"
	lazyMageLocale.enUS.ACTION_TTS.conjureWater     = "Conjure Water"
	lazyMageLocale.enUS.ACTION_TTS.counter          = "Counterspell"
	lazyMageLocale.enUS.ACTION_TTS.dampenMagic      = "Dampen Magic"
	lazyMageLocale.enUS.ACTION_TTS.detectMagic      = "Detect Magic"
	lazyMageLocale.enUS.ACTION_TTS.evocation        = "Evocation"
	lazyMageLocale.enUS.ACTION_TTS.explosion        = "Arcane Explosion"
	lazyMageLocale.enUS.ACTION_TTS.fireball         = "Fireball"
	lazyMageLocale.enUS.ACTION_TTS.fireBlast        = "Fire Blast"
	lazyMageLocale.enUS.ACTION_TTS.fireWard         = "Fire Ward"
	lazyMageLocale.enUS.ACTION_TTS.flamestrike      = "Flamestrike"
	lazyMageLocale.enUS.ACTION_TTS.frostArmor       = "Frost Armor"
	lazyMageLocale.enUS.ACTION_TTS.frostbolt        = "Frostbolt"
	lazyMageLocale.enUS.ACTION_TTS.frostNova        = "Frost Nova"
	lazyMageLocale.enUS.ACTION_TTS.frostWard        = "Frost Ward"
	lazyMageLocale.enUS.ACTION_TTS.iceArmor         = "Ice Armor"
	lazyMageLocale.enUS.ACTION_TTS.iceBarrier       = "Ice Barrier"
	lazyMageLocale.enUS.ACTION_TTS.iceBlock         = "Ice Block"
	lazyMageLocale.enUS.ACTION_TTS.intellect        = "Arcane Intellect"
	lazyMageLocale.enUS.ACTION_TTS.mageArmor        = "Mage Armor"
	lazyMageLocale.enUS.ACTION_TTS.manaShield       = "Mana Shield"
	lazyMageLocale.enUS.ACTION_TTS.missiles         = "Arcane Missiles"
	lazyMageLocale.enUS.ACTION_TTS.pig              = "Polymorph: Pig"
	lazyMageLocale.enUS.ACTION_TTS.pom              = "Presence of Mind"
	lazyMageLocale.enUS.ACTION_TTS.pyroblast        = "Pyroblast"
	lazyMageLocale.enUS.ACTION_TTS.removeCurse      = "Remove Curse"
	lazyMageLocale.enUS.ACTION_TTS.scorch           = "Scorch"
	lazyMageLocale.enUS.ACTION_TTS.sheep            = "Polymorph"
	lazyMageLocale.enUS.ACTION_TTS.slowFall         = "Slow Fall"
	lazyMageLocale.enUS.ACTION_TTS.teleDarnassus    = "Teleport: Darnassus"
	lazyMageLocale.enUS.ACTION_TTS.teleIronforge    = "Teleport: Ironforge"
	lazyMageLocale.enUS.ACTION_TTS.teleOgrimmar     = "Teleport: Ogrimmar"
	lazyMageLocale.enUS.ACTION_TTS.teleStormwind    = "Teleport: Stormwind"
	lazyMageLocale.enUS.ACTION_TTS.teleThunderBluff = "Teleport: Thunder Bluff"
	lazyMageLocale.enUS.ACTION_TTS.teleUndercity    = "Teleport: Undercity"
	lazyMageLocale.enUS.ACTION_TTS.turtle           = "Polymorph: Turtle"
	lazyMageLocale.enUS.ACTION_TTS.portDarnassus    = "Portal: Darnassus"
	lazyMageLocale.enUS.ACTION_TTS.portIronforge    = "Portal: Ironforge"
	lazyMageLocale.enUS.ACTION_TTS.portOgrimmar     = "Portal: Ogrimmar"
	lazyMageLocale.enUS.ACTION_TTS.portStormwind    = "Portal: Stormwind"
	lazyMageLocale.enUS.ACTION_TTS.portThunderBluff = "Portal: Thunder Bluff"
	lazyMageLocale.enUS.ACTION_TTS.portUndercity    = "Portal: Undercity"
	
	-- LazyMage.lua
	MAGE_ADDON_LOADED = " loaded. Powered by "
	
	-- ParseMage.lua
	function lazyMage.CustomLocaleHelp() return [[<H2>Mage Criteria:</H2>]] end
	
	if (locale == "ruRU") then
		
		lazyMageLocale.ruRU.ACTION_TTS.amplifyMagic     = "Усиление магии"
		lazyMageLocale.ruRU.ACTION_TTS.arcanePower      = "Мощь тайной магии"
		lazyMageLocale.ruRU.ACTION_TTS.blastWave        = "Взрывная волна"
		lazyMageLocale.ruRU.ACTION_TTS.blink            = "Скачок"
		lazyMageLocale.ruRU.ACTION_TTS.blizzard         = "Снежная буря"
		lazyMageLocale.ruRU.ACTION_TTS.brilliance       = "Чародейская гениальность"
		lazyMageLocale.ruRU.ACTION_TTS.coldSnap         = "Холодная хватка"
		lazyMageLocale.ruRU.ACTION_TTS.combustion       = "Возгорание"
		lazyMageLocale.ruRU.ACTION_TTS.coneCold         = "Конус холода"
		lazyMageLocale.ruRU.ACTION_TTS.conjureAgate     = "Сотворение агата маны"
		lazyMageLocale.ruRU.ACTION_TTS.conjureCitrine   = "Сотворение цитрина маны"
		lazyMageLocale.ruRU.ACTION_TTS.conjureFood      = "Сотворение пищи"
		lazyMageLocale.ruRU.ACTION_TTS.conjureJade      = "Сотворение нефрита маны"
		lazyMageLocale.ruRU.ACTION_TTS.conjureRuby      = "Сотворение рубина маны"
		lazyMageLocale.ruRU.ACTION_TTS.conjureWater     = "Сотворение воды"
		lazyMageLocale.ruRU.ACTION_TTS.counter          = "Антимагия"
		lazyMageLocale.ruRU.ACTION_TTS.dampenMagic      = "Ослабление магии"
		lazyMageLocale.ruRU.ACTION_TTS.detectMagic      = "Распознавание магии"
		lazyMageLocale.ruRU.ACTION_TTS.evocation        = "Прилив сил"
		lazyMageLocale.ruRU.ACTION_TTS.explosion        = "Чародейский взрыв"
		lazyMageLocale.ruRU.ACTION_TTS.fireball         = "Огненный шар"
		lazyMageLocale.ruRU.ACTION_TTS.fireBlast        = "Огненный взрыв"
		lazyMageLocale.ruRU.ACTION_TTS.fireWard         = "Защита от огня"
		lazyMageLocale.ruRU.ACTION_TTS.flamestrike      = "Огненный столб"
		lazyMageLocale.ruRU.ACTION_TTS.frostArmor       = "Морозный доспех"
		lazyMageLocale.ruRU.ACTION_TTS.frostbolt        = "Ледяная стрела"
		lazyMageLocale.ruRU.ACTION_TTS.frostNova        = "Кольцо льда"
		lazyMageLocale.ruRU.ACTION_TTS.frostWard        = "Защита от магии льда"
		lazyMageLocale.ruRU.ACTION_TTS.iceArmor         = "Ледяной доспех"
		lazyMageLocale.ruRU.ACTION_TTS.iceBarrier       = "Ледяная преграда"
		lazyMageLocale.ruRU.ACTION_TTS.iceBlock         = "Ледяная глыба"
		lazyMageLocale.ruRU.ACTION_TTS.intellect        = "Чародейский интеллект"
		lazyMageLocale.ruRU.ACTION_TTS.mageArmor        = "Магический доспех"
		lazyMageLocale.ruRU.ACTION_TTS.manaShield       = "Щит маны"
		lazyMageLocale.ruRU.ACTION_TTS.missiles         = "Чародейские стрелы"
		lazyMageLocale.ruRU.ACTION_TTS.pig              = "Превращение: свинья"
		lazyMageLocale.ruRU.ACTION_TTS.pom              = "Величие разума"
		lazyMageLocale.ruRU.ACTION_TTS.pyroblast        = "Огненная глыба"
		lazyMageLocale.ruRU.ACTION_TTS.removeCurse      = "Снятие проклятия"
		lazyMageLocale.ruRU.ACTION_TTS.scorch           = "Ожог"
		lazyMageLocale.ruRU.ACTION_TTS.sheep            = "Превращение"
		lazyMageLocale.ruRU.ACTION_TTS.slowFall         = "Замедленное падение"
		lazyMageLocale.ruRU.ACTION_TTS.teleDarnassus    = "Телепортация: Дарнас"
		lazyMageLocale.ruRU.ACTION_TTS.teleIronforge    = "Телепортация: Стальгорн"
		lazyMageLocale.ruRU.ACTION_TTS.teleOgrimmar     = "Телепортация: Оргриммар"
		lazyMageLocale.ruRU.ACTION_TTS.teleStormwind    = "Телепортация: Штормград"
		lazyMageLocale.ruRU.ACTION_TTS.teleThunderBluff = "Телепортация: Громовой Утес"
		lazyMageLocale.ruRU.ACTION_TTS.teleUndercity    = "Телепортация: Подгород"
		lazyMageLocale.ruRU.ACTION_TTS.turtle           = "Превращение: черепаха"
		lazyMageLocale.ruRU.ACTION_TTS.portDarnassus    = "Портал: Дарнас"
		lazyMageLocale.ruRU.ACTION_TTS.portIronforge    = "Портал в Стальгорн"
		lazyMageLocale.ruRU.ACTION_TTS.portOgrimmar     = "Портал в Оргриммар"
		lazyMageLocale.ruRU.ACTION_TTS.portStormwind    = "Портал в Штормград"
		lazyMageLocale.ruRU.ACTION_TTS.portThunderBluff = "Портал в Громовой Утес"
		lazyMageLocale.ruRU.ACTION_TTS.portUndercity    = "Портал в Подгород"
		
		-- LazyMage.lua
		MAGE_ADDON_LOADED = " загружен. Работает от "
		
		-- ParseMage.lua
		function lazyMage.CustomLocaleHelp() return [[<H2>Критерии Мага:</H2>]] end
		
		elseif (locale == "deDE") then
		
		lazyMageLocale.deDE.ACTION_TTS.conjureAgate     = "Mana-Achat herbeizaubern"
		lazyMageLocale.deDE.ACTION_TTS.conjureCitrine   = "Mana-Citrin herbeizaubern"
		lazyMageLocale.deDE.ACTION_TTS.conjureJade      = "Mana-Jadestein herbeizaubern"
		lazyMageLocale.deDE.ACTION_TTS.conjureRuby      = "Mana-Rubin herbeizaubern"
		lazyMageLocale.deDE.ACTION_TTS.explosion        = "Arkane Explosion"
		lazyMageLocale.deDE.ACTION_TTS.frostArmor       = "Frostr\195\188stung"
		lazyMageLocale.deDE.ACTION_TTS.iceArmor         = "Eisr\195\188stung"
		
		elseif (locale == "frFR") then
		
		lazyMageLocale.frFR.ACTION_TTS.conjureAgate     = "Invocation d'une agate de mana"
		lazyMageLocale.frFR.ACTION_TTS.conjureCitrine   = "Invocation d'une citrine de mana"
		lazyMageLocale.frFR.ACTION_TTS.conjureJade      = "Invocation d'une jade de mana"
		lazyMageLocale.frFR.ACTION_TTS.conjureRuby      = "Invocation d'un rubis de mana"
		lazyMageLocale.frFR.ACTION_TTS.explosion        = "Explosion des arcanes"
		lazyMageLocale.frFR.ACTION_TTS.frostArmor       = "Armure de givre"
		lazyMageLocale.frFR.ACTION_TTS.iceArmor         = "Armure de glace"
		
	end
end	